config-version: 1
############# OldCombatMechanics Plugin by gvlfm78 and Rayzr522 #############
#                                                                           #
# Bukkit Page: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics/     #
# Spigot Page: https://www.spigotmc.org/resources/oldcombatmechanics.19510/ #
# GitHub Page: https://github.com/gvlfm78/BukkitOldCombatMechanics/         #
#                                                                           #
#############################################################################

# This is to toggle the update checker
update-checker: true

disable-attack-cooldown:
  # This is to disable the attack cooldown
  enabled: true
  worlds: []

################################################################
##### EVERYTHING BELOW THIS COMMENT IS NOT YET IMPLEMENTED #####
################################################################

old-axe-damage:
  # This is to set the axe damage as in pre-1.9
  enabled: false
  worlds: []

disable-player-collisions:
  # This is to disable player collisions
  enabled: false
  worlds: []

disable-knockback-attack:
  # This is to disable the special sword attack that knocks back
  enabled: false
  worlds: []

disable-shields:
  # This is to disable the use of shields
  enabled: false
  worlds: []