# OldCombatMechanics Plugin by gvlfm78
# This is to disable the update checker if for whatever reason you deemed it unneccessary
update-checker: true
# This is the item that will be placed in the legs slot when no armour is present
item:
    type: wood_button
    custom-name: '&5Attack Speed Fixer'
    lore1:
    lore2: