main: gvlfm78.plugin.OldCombatMechanics.OCMMain
name: OldCombatMechanics
version: 0.4
author: gvlfm78
description: Removes weapon cooldown in 1.9
website: http://dev.bukkit.org/bukkit-plugins/oldcombatmechanics
load: POSTWORLD

commands:
  OldCombatMechanics:
   description: OldCombatMechanics's main command
   aliases: ocm